package com.rwy.spider.bean.quartz;

// Generated 2014-10-28 8:26:25 by Hibernate Tools 4.0.0

import javax.persistence.*;

/**
 * QrtzBlobTriggers generated by hbm2java
 */
@Entity
@Table(name = "qrtz_blob_triggers", catalog = "spider")
public class QrtzBlobTriggers implements java.io.Serializable {

	private QrtzBlobTriggersId id;
	private QrtzTriggers qrtzTriggers;
	private byte[] blobData;

	public QrtzBlobTriggers() {
	}

	public QrtzBlobTriggers(QrtzTriggers qrtzTriggers) {
		this.qrtzTriggers = qrtzTriggers;
	}

	public QrtzBlobTriggers(QrtzTriggers qrtzTriggers, byte[] blobData) {
		this.qrtzTriggers = qrtzTriggers;
		this.blobData = blobData;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "schedName", column = @Column(name = "SCHED_NAME", nullable = false, length = 120)),
			@AttributeOverride(name = "triggerName", column = @Column(name = "TRIGGER_NAME", nullable = false, length = 200)),
			@AttributeOverride(name = "triggerGroup", column = @Column(name = "TRIGGER_GROUP", nullable = false, length = 200)) })
	public QrtzBlobTriggersId getId() {
		return this.id;
	}

	public void setId(QrtzBlobTriggersId id) {
		this.id = id;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public QrtzTriggers getQrtzTriggers() {
		return this.qrtzTriggers;
	}

	public void setQrtzTriggers(QrtzTriggers qrtzTriggers) {
		this.qrtzTriggers = qrtzTriggers;
	}

    @Lob
	@Column(name = "BLOB_DATA")
	public byte[] getBlobData() {
		return this.blobData;
	}

	public void setBlobData(byte[] blobData) {
		this.blobData = blobData;
	}

}
