package com.rwy.spider.bean.quartz;

// Generated 2014-10-28 8:26:25 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * QrtzCalendars generated by hbm2java
 */
@Entity
@Table(name = "qrtz_calendars", catalog = "spider")
public class QrtzCalendars implements java.io.Serializable {

	private QrtzCalendarsId id;
	private byte[] calendar;

	public QrtzCalendars() {
	}

	public QrtzCalendars(QrtzCalendarsId id, byte[] calendar) {
		this.id = id;
		this.calendar = calendar;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "schedName", column = @Column(name = "SCHED_NAME", nullable = false, length = 120)),
			@AttributeOverride(name = "calendarName", column = @Column(name = "CALENDAR_NAME", nullable = false, length = 200)) })
	public QrtzCalendarsId getId() {
		return this.id;
	}

	public void setId(QrtzCalendarsId id) {
		this.id = id;
	}

	@Column(name = "CALENDAR", nullable = false)
	public byte[] getCalendar() {
		return this.calendar;
	}

	public void setCalendar(byte[] calendar) {
		this.calendar = calendar;
	}

}
